---
all:
  children:
    workstations:
      hosts:
        apollo:
          ansible_host: localhost
          ansible_connection: local
        hephaestus:
          ansible_host: localhost
          ansible_connection: local
        artemis:
          ansible_host: localhost
          ansible_connection: local

    # Test VMs
    test:
      vars:
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -o PubkeyAuthentication=no
        # Disable secrets-dependent features for testing
        tailscale_state: absent
        wireguard_state: absent
      hosts:
        arch-test:
          ansible_host: 10.97.9.143
          ansible_user: gorschu
