---
# KDE Plasma packages
kde_packages:
  - plasma-meta
  - plasma-login-manager

# KDE applications
kde_applications:
  - ark
  - dolphin
  - gwenview
  - kate
  - kdeconnect
  - konsole
  - krdc
  - kwallet
  - kwallet-pam
  - kwalletmanager
  - okular
  - spectacle
